- name: set database password as fact
  no_log: true
  block:
    - name: Read Database password
      shell: my_print_defaults client | grep password | cut -d "=" -f 2
      register: cmd_output
    - name: Set database password as fact
      set_fact:
        db_password: "{{ cmd_output.stdout }}"

- name: Make sure database exists
  mysql_db:
    name: "{{ ansible_user }}_ephios"
    state: present

- name: set database url
  set_fact:
    database_url: "mysql://{{ ansible_user }}:{{ db_password }}@localhost/{{ ansible_user }}_ephios"
