---
- name: Install ephios on an uberspace account
  hosts: uberspace_instances
  strategy: free
  vars:
    package_name: ephios[mysql,pgsql,redis]
  gather_facts: false
  roles:
    - uberspace_ephios